[deploy]
bucket = 'jessbk-cfn-artifacts'
region = 'us-east-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://jessbkcloudcampus.com'
EnvBackendUrl = 'https://api.jessbkcloudcampus.com'