[deploy]
bucket = 'jessbk-cfn-artifacts'
region = 'us-east-1'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'jess-bk/aws-bootcamp-cruddur-2023'
ArtifactBucketName = 'jessbk-codepipeline-cruddur-artifacts'
BuildSpec = 'backend-flask/buildspec.yml'